### ISSUE TITLE
What is the license for the code in this repo? Is it open source?

### ISSUE THREAD

**Issue by jrgibson** [Codehut/DataEncrypterDecrypterCSharp#1]
Hello,

Thank you for this repo and the post at https://www.c-sharpcorner.com/UploadFile/f8fa6c/data-encryption-and-decryption-in-C-Sharp/ . I would like to build on this code in a commercial project but wanted to make sure that it was free to use. Please let me know.

Thank you,
  – Jeremy

**Comment by janaks09** [comment]
Hi @jrgibson ,

Yup it is free to use!
